import { createBulkLanguage } from '@/lib/services/language.services';

export default async function seedLanguages() {
	await createBulkLanguage([
		{ title: 'English' },
		{ title: 'Spanish' },
		{ title: 'French' },
		{ title: 'German' },
		{ title: 'Mandarin' },
		{ title: 'Hindi' },
		{ title: 'Arabic' },
		{ title: 'Portuguese' },
		{ title: 'Bengali' },
		{ title: 'Russian' },
		{ title: 'Japanese' },
		{ title: 'Punjabi' },
		{ title: 'Korean' },
		{ title: 'Italian' },
		{ title: 'Turkish' },
		{ title: 'Vietnamese' },
		{ title: 'Urdu' },
		{ title: 'Persian' },
		{ title: 'Malay' },
		{ title: 'Thai' },
		{ title: 'Swahili' },
		{ title: 'Dutch' },
		{ title: 'Greek' },
		{ title: 'Czech' },
		{ title: 'Swedish' },
		{ title: 'Romanian' },
		{ title: 'Hungarian' },
		{ title: 'Polish' },
		{ title: 'Ukrainian' },
		{ title: 'Finnish' },
		{ title: 'Norwegian' },
		{ title: 'Danish' },
		{ title: 'Hebrew' },
		{ title: 'Indonesian' },
		{ title: 'Filipino' },
		{ title: 'Malayalam' },
		{ title: 'Tamil' },
		{ title: 'Telugu' },
		{ title: 'Marathi' },
		{ title: 'Gujarati' },
		{ title: 'Kannada' },
		{ title: 'Burmese' },
		{ title: 'Khmer' },
		{ title: 'Lao' },
		{ title: 'Amharic' },
		{ title: 'Yoruba' },
		{ title: 'Zulu' },
		{ title: 'Hausa' },
	]);
}
